p <- read.table("household_power_consumption.txt",skip=1,sep=";")
names(p) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
sub_p <- subset(p,p$Date=="1/2/2007" | p$Date =="2/2/2007")
sub_p$Date <- as.Date(sub_p$Date, format="%d/%m/%Y")
sub_p$Time <- strptime(sub_p$Time, format="%H:%M:%S")
sub_p[1:1440,"Time"] <- format(sub_p[1:1440,"Time"],"2007-02-01 %H:%M:%S")
sub_p[1441:2880,"Time"] <- format(sub_p[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(sub_p$Time,as.numeric(as.character(sub_p$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)") 
title(main="Global Active Power Vs Time")
dev.copy(png, file = "plot2.png")
dev.off()